### ISSUE TITLE
List data by paper

### ISSUE THREAD

**Issue by coatless** [tmsalab/edmdata#8]
Something like: 

```yaml
paper: 
  key: BibID
  data: items_name
  data: qmatrix_name
```

From that, the `@references` section could be populated with paper links/reference information.
